### ISSUE TITLE
backdoor.py & ofp_decrypt.py doesn't work for realme 3 pro

### ISSUE THREAD

**Issue by SauravDharwadkar** [bkerler/oppo_decrypt#10]
ofp_decrypt.py cann't find key or no way specified
as well backdoor doesnt work tried all things but doesnt

**Comment by bkerler** [comment]
The readme file was refering to the wrong file. Commit bfb6499 fixes that. Please try again.

**Comment by bkerler** [comment]
Use ofp_extract.py for extraction.

**Comment by SauravDharwadkar** [comment]
tried but only xml files extracting

**Comment by zeheater** [comment]
@bkerler , i think you made a typo.
line 222: should be
`elif: child.tag in ["Data"]: `

after i change that, it extracts just fine. (haven't tested it, i don't have my device with me now)

**Comment by SauravDharwadkar** [comment]
python3 ofp_extract.py [myops.ofp]
but it asking <startoffset> <length>
where to find ?

**Comment by bkerler** [comment]
Should be fixed in 755b5d7, please test
