### ISSUE TITLE
oppo A92 cph2509 failed to extract

### ISSUE THREAD

**Issue by xteamcrew** [bkerler/oppo_decrypt#13]
i just try to extract ofp oppo a92 but failed and give me blank folder
please add oppo A92 key.
E:\CPH2059>python ofp_extract.py CPH2059PU_11_A.11_200406_18ab13a8.ofp
Traceback (most recent call last):
  File "ofp_extract.py", line 252, in <module>
    main()
  File "ofp_extract.py", line 219, in main
    start = int(item.attrib["SizeInSectorInSrc"]) * pagesize
KeyError: 'SizeInSectorInSrc'

**Comment by bkerler** [comment]
I will have a look :)

**Comment by bkerler** [comment]
Fixed with commit 755b5d7
