### ISSUE TITLE
Is there any possibility to decrypt Oppo MTK ofp files?

### ISSUE THREAD

**Issue by shadabmozaffar** [bkerler/oppo_decrypt#15]
Hi ViperBJK!

Thank you for your nice piece of code to extract ofp file. I have successfully converted it to delphi. 

As I can see, it only supports QC firmware. I could not find any way to find page size sign in all MTK firmware I have. Also random decryption did not help.

Can you please shed some light or help me to work on MTK firmware decryption?

Br,

**Comment by bkerler** [comment]
Yes. It will be supported shortly. Consider donating as soon as it's up :)

**Comment by shadabmozaffar** [comment]
Hi!

I will be more than happy to do that. Please share a payment method.

Br,
Shadab

**Comment by Sandeepa167** [comment]
> Hi ViperBJK!
> 
> Thank you for your nice piece of code to extract ofp file. I have successfully converted it to delphi.
> 
> As I can see, it only supports QC firmware. I could not find any way to find page size sign in all MTK firmware I have. Also random decryption did not help.
> 
> Can you please shed some light or help me to work on MTK firmware decryption?
> 
> Br,

hi ,

can you share your delphi converted code ?

thanks !
