### ISSUE TITLE
oppo a57t xml.etree.ElementTree.ParseError

### ISSUE THREAD

**Issue by kwaiching** [bkerler/oppo_decrypt#17]
Traceback (most recent call last):
  File "ofp_extract.py", line 252, in <module>
    main()
  File "ofp_extract.py", line 205, in main
    root = ET.fromstring(xml)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1321, in XML
    return parser.close()
xml.etree.ElementTree.ParseError: no element found: line 2, column 9

**Comment by bkerler** [comment]
Can you post a link to the firmware ? Looks like they changed the xml.

**Comment by kwaiching** [comment]
> Can you post a link to the firmware ? Looks like they changed the xml.

链接: https://pan.baidu.com/s/1NdS8cK2KEkS7rQ_9wLu8qQ 提取码: gj1h

**Comment by bkerler** [comment]
Fixed with commit 755b5d7
