### ISSUE TITLE
errors while extracting .ofp file of realme x50(china)

### ISSUE THREAD

**Issue by h45251880** [bkerler/oppo_decrypt#20]
fail message:Unknown pagesize. Aborting

can you plz do support this device too../
firmware link : https://drive.google.com/file/d/1HtK1kEsUj61yosMQ9UhofxnlVS_sdMWq/view?usp=sharing

**Comment by bkerler** [comment]
Can you upload the full firmware incl. flasher tool ?

**Comment by bkerler** [comment]
This ofp seems to be no ofp at all, but instead an encrypted zip file. Or oppo now changed to use encrypted zip :)
