### ISSUE TITLE
can't find the DA_FILE

### ISSUE THREAD

**Issue by paindustry** [bkerler/oppo_decrypt#21]
Thanks it worked with "RMX1941EX_11_A.10_190507_c80b7906" looks like everything has been extracted but i can't find the DA_FILE (DownloadAgent.bin)

**Comment by bkerler** [comment]
the da_file isn't in the ofp file, see efuse files it should be called "MTK_AllInOne_DA.bin", maybe it's statically linked in the database or exe file.

**Comment by paindustry** [comment]
could you please do support so that the "MTK_AllInOne_DA.bin" file can be extracted too :)

**Comment by bkerler** [comment]
Hi, as said, the MTK_AllInOne_DA.bin is not part of the ofp, it seems to be delivered separately.
