### ISSUE TITLE
run command but no output

### ISSUE THREAD

**Issue by siddhrsh** [bkerler/oppo_decrypt#22]
via windows 
PS E:\New folder> python3 ofp_mtk_decrypt.py RMX1941EX_11_A.28.ofp extract
PS E:\New folder> python3 ofp_mtk_decrypt.py RMX1941EX_11_A.28.ofp E:\New folder
PS E:\New folder>

via wsl2
root@SID:/mnt/e/New folder# ./ofp_mtk_decrypt.py RMX1941.ofp
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/359.
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/359.
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/359.
from: too many arguments
from: too many arguments
from: too many arguments
./ofp_mtk_decrypt.py: line 11: syntax error near unexpected token `('
./ofp_mtk_decrypt.py: line 11: `def swap(ch):'

**Comment by bkerler** [comment]
Hi, as stated in the readme, you need to also give the name of the directory to extract to:
in wsl: python3 ofp_mtk_decrypt.py RMX1941.ofp extractdir

Also if you use spaces in the names, you need to use quotationmarks as well:

python3 ofp_mtk_extract.py RMX1941EX_11_A.28.ofp "E:\New folder"

**Comment by siddhrsh** [comment]
> Hi, as stated in the readme, you need to also give the name of the directory to extract to:
> in wsl: python3 ofp_mtk_decrypt.py RMX1941.ofp extractdir
> 
> Also if you use spaces in the names, you need to use quotationmarks as well:
> 
> python3 ofp_mtk_extract.py RMX1941EX_11_A.28.ofp "E:\New folder"

PS E:\New folder> python3 ofp_mtk_extract.py RMX1941EX_11_A.28.ofp "E:\New folder"
PS E:\New folder>
also i tried ofp_mtk_decrypt.py

**Comment by siddhrsh** [comment]
tried via ubuntu 
python3 ofp_mtk_decrypt.py RMX1941EX_11_A.28.ofp extract
Unknown key. Please ask the author for support :)

**Comment by siddhrsh** [comment]
> Hi, as stated in the readme, you need to also give the name of the directory to extract to:
> in wsl: python3 ofp_mtk_decrypt.py RMX1941.ofp extractdir
> 
> Also if you use spaces in the names, you need to use quotationmarks as well:
> 
> python3 ofp_mtk_extract.py RMX1941EX_11_A.28.ofp "E:\New folder"

tried via ubuntu
python3 ofp_mtk_decrypt.py RMX1941EX_11_A.28.ofp extract
Unknown key. Please ask the author for support :)

**Comment by paindustry** [comment]
it worked with RMX1941EX_11_A.10
maybe for versions vA.20 and above have used a different key.

> > Hi, as stated in the readme, you need to also give the name of the directory to extract to:
> > in wsl: python3 ofp_mtk_decrypt.py RMX1941.ofp extractdir
> > Also if you use spaces in the names, you need to use quotationmarks as well:
> > python3 ofp_mtk_extract.py RMX1941EX_11_A.28.ofp "E:\New folder"
> 
> error on windows, wsl2 & ubuntu
> python3 ofp_mtk_decrypt.py RMX1941EX_11_A.28.ofp extract
> Unknown key. Please ask the author for support :)

**Comment by siddhrsh** [comment]
> it worked with RMX1941EX_11_A.10
> maybe for versions vA.20 and above have used a different key.
> 
> > > Hi, as stated in the readme, you need to also give the name of the directory to extract to:
> > > in wsl: python3 ofp_mtk_decrypt.py RMX1941.ofp extractdir
> > > Also if you use spaces in the names, you need to use quotationmarks as well:
> > > python3 ofp_mtk_extract.py RMX1941EX_11_A.28.ofp "E:\New folder"
> > 
> > 
> > error on windows, wsl2 & ubuntu
> > python3 ofp_mtk_decrypt.py RMX1941EX_11_A.28.ofp extract
> > Unknown key. Please ask the author for support :)

tried on a17 too same issue
too many changes from a10 to a28 so i want the latest i have extracted recovery.cpio.gz too but there is no sbin/recovery

**Comment by AungKhantMin** [comment]
if i am not wrong you can only extracted the key from mtk download tool

**Comment by AungKhantMin** [comment]
> > it worked with RMX1941EX_11_A.10
> > maybe for versions vA.20 and above have used a different key.
> > > > Hi, as stated in the readme, you need to also give the name of the directory to extract to:
> > > > in wsl: python3 ofp_mtk_decrypt.py RMX1941.ofp extractdir
> > > > Also if you use spaces in the names, you need to use quotationmarks as well:
> > > > python3 ofp_mtk_extract.py RMX1941EX_11_A.28.ofp "E:\New folder"
> > > 
> > > 
> > > error on windows, wsl2 & ubuntu
> > > python3 ofp_mtk_decrypt.py RMX1941EX_11_A.28.ofp extract
> > > Unknown key. Please ask the author for support :)
> 
> tried on a17 too same issue
> too many changes from a10 to a28 so i want the latest
> 
> i have extracted recovery.cpio.gz too but there is no sbin/recovery waiting for @bkerler reply

if i am not wrong you can only extracted the key from mtk download tool

**Comment by bkerler** [comment]
I will have a look ....

**Comment by AungKhantMin** [comment]
> I will have a look ....

I created a pull request for this issue @bkerler

**Comment by bkerler** [comment]
Fixed with commit 5696b05ac3b07921ab2f698f9aae600c9805f3f0 thanks to AungKhantMin

**Comment by FreyjadourF** [comment]
I'm having the same problem, tried extracting ofp from CPH2127PU_11_A.23_200826_6aade87b.ofp
