### ISSUE TITLE
Unknown pagesize error for Realme X ofp

### ISSUE THREAD

**Issue by gonejack** [bkerler/oppo_decrypt#24]
https://download.c.realme.com/flash/Flash_Package/X/RMX1901EX_11_C.03.ofp

```
> python3 ofp_qc_extract.py RMX1901EX_11_C.03.ofp out
Unknown pagesize. Aborting
````

**Comment by yssreddy1961** [comment]
Tested,Now working with latest 3.52 release edl
$ python3 ofp_qc_decrypt.py ../RMX1901EX_11_C.03.ofp ../oppo1
Zip file detected, trying to decrypt files
Extracting boot.img to ../oppo1
Extracting FlashingConfig.xml to ../oppo1
Extracting system.img to ../oppo1
Extracting vbmeta.img to ../oppo1
Extracting vendor.img to ../oppo1
Files extracted to ../oppo1


issue can be closed

**Comment by gonejack** [comment]
Well job
