### ISSUE TITLE
  File "D:\Desktop\R9s_11_A.26_180703\ofp_qc_extract.py", line 8, in <module>     from Crypto.Cipher import AES ModuleNotFoundError: No module named 'Crypto'

### ISSUE THREAD

**Issue by 735394006** [bkerler/oppo_decrypt#26]
File "D:\Desktop\R9s_11_A.26_180703\ofp_qc_extract.py", line 8, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

**Comment by bkerler** [comment]
Please install the requirements.txt as stated in the README. pip3 install cryptodome.
