### ISSUE TITLE
What's the situation? Is it an extraction error? What should I do? Thank you

### ISSUE THREAD

**Issue by yb2xm13** [bkerler/oppo_decrypt#29]
E:\软件\oppok3\oppo_decrypt-master>ofp_qc_extract.py PCGM00_11_A.04_190626_dbcddc4a.ofp "E:\软件\oppok3\oppo_decrypt-master\k3"
Extracting prog_firehose_ddr.elf
Extracting persist.img
Extracting cache.img
Extracting system.img
**Error on hashes. File might be broken ! Crypt**
Extracting userdata.img
**Error on hashes. File might be broken ! Crypt**
Extracting gpt_main0.bin
Extracting gpt_backup0.bin
Extracting xbl.elf
Extracting xbl_config.elf
Extracting gpt_main1.bin
Extracting gpt_backup1.bin
Extracting gpt_main2.bin
Extracting gpt_backup2.bin
Extracting oppo18041.bin
Extracting oppo18038.bin
Extracting gpt_main3.bin
Extracting gpt_backup3.bin
Extracting aop.mbn
Extracting tz.mbn
Extracting hyp.mbn
Extracting hyp.mbn
Extracting NON-HLOS.bin
Extracting BTFM.bin
Extracting abl.elf
Extracting dspso.bin
Extracting km4.mbn
Extracting boot.img
Extracting cmnlib.mbn
Extracting cmnlib64.mbn
Extracting devcfg.mbn
Extracting qupv3fw.elf
Extracting vendor.img
Error on hashes. File might be broken ! Crypt
Extracting vbmeta.img
Extracting recovery.img
Extracting dtbo.img
Extracting storsec.mbn
Extracting oppo_sec.mbn
Extracting sec_smt.dat
Extracting dpAP.mbn
Extracting dpMSA.mbn
Extracting splash.img
Extracting logfs_ufs_8mb.bin
Extracting gpt_main4.bin
Extracting gpt_backup4.bin
Extracting dynamic_nvbk.bin
Extracting static_nvbk.bin
Extracting emmc_fw.bin
Extracting opporeserve2.img
Error on hashes. File might be broken ! Crypt
Extracting DRIVER.ISO
Extracting gpt_main5.bin
Extracting gpt_backup5.bin
Extracting Setting.xml
Extracting Projectconfig.xml
Extracting rawprogram0.xml
Extracting rawprogram1.xml
Extracting rawprogram2.xml
Extracting rawprogram3.xml
Extracting rawprogram4.xml
Extracting rawprogram5.xml
Extracting patch0.xml
Extracting patch1.xml
Extracting patch2.xml
Extracting patch3.xml
Extracting patch4.xml
Extracting patch5.xml
Extracting provision_hynix.xml
Extracting provision_samsung.xml
Extracting provision_micron.xml
Extracting ChainedTableOfDigests_18041_all.bin.
Extracting ChainedTableOfDigests_18041_persist_no_userdata_yes.bin.
Extracting ChainedTableOfDigests_18041_persist_yes_userdata_yes.bin.
Extracting ChainedTableOfDigests_18041_persist_yes_userdata_no.bin.
Extracting ChainedTableOfDigests_18041_persist_no_userdata_no.bin.
Extracting ChainedTableOfDigests_18038_all.bin.
Extracting ChainedTableOfDigests_18038_persist_no_userdata_yes.bin.
Extracting ChainedTableOfDigests_18038_persist_yes_userdata_yes.bin.
Extracting ChainedTableOfDigests_18038_persist_yes_userdata_no.bin.
Extracting ChainedTableOfDigests_18038_persist_no_userdata_no.bin.
Extracting ChainedTableOfDigests_pre_provision.bin.
Extracting ChainedTableOfDigests_provision_hynix.bin.
Extracting ChainedTableOfDigests_provision_samsung.bin.
Extracting ChainedTableOfDigests_provision_micron.bin.
Extracting DigestsToSign_18041_all.bin.mbn.
Extracting DigestsToSign_18041_persist_no_userdata_yes.bin.mbn.
Extracting DigestsToSign_18041_persist_yes_userdata_yes.bin.mbn.
Extracting DigestsToSign_18041_persist_yes_userdata_no.bin.mbn.
Extracting DigestsToSign_18041_persist_no_userdata_no.bin.mbn.
Extracting DigestsToSign_18038_all.bin.mbn.
Extracting DigestsToSign_18038_persist_no_userdata_yes.bin.mbn.
Extracting DigestsToSign_18038_persist_yes_userdata_yes.bin.mbn.
Extracting DigestsToSign_18038_persist_yes_userdata_no.bin.mbn.
Extracting DigestsToSign_18038_persist_no_userdata_no.bin.mbn.
Extracting DigestsToSign_pre_provision.bin.mbn.
Extracting DigestsToSign_provision_hynix.bin.mbn.
Extracting DigestsToSign_provision_samsung.bin.mbn.
Extracting DigestsToSign_provision_micron.bin.mbn.
Done. Extracted files to E:\软件\oppok3\oppo_decrypt-master\k3

**Comment by bkerler** [comment]
The files should be fine. The checksum calculation algorithm for sparse images isn't yet reversed, that's the reason for this error.
