### ISSUE TITLE
Crypto.Cipher import AES ModuleNotFoundError: No module named 'Crypto'

### ISSUE THREAD

**Issue by krigeta** [bkerler/oppo_decrypt#37]
I have installed the requirements.txt as you can see in the below image buut why this error is coming?

```
from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'
```

![Screenshot (35)](https://user-images.githubusercontent.com/75309361/120112244-ae625d00-c192-11eb-99c5-6a59a0feba20.png)

**Comment by MlgmXyysd** [comment]
try install Crypto

**Comment by bkerler** [comment]
Pip3 install pycryptodome ;)

**Comment by krigeta** [comment]
Let me check, I will let you know if it worked or not

**Comment by bkerler** [comment]
I consider this to be solved, as it's in the readme as well :)
