### ISSUE TITLE
Unknown key. Please ask the author for support :)

### ISSUE THREAD

**Issue by ShinoNuma** [bkerler/oppo_decrypt#38]
Hi @bkerler,

I've recently got the firmware file (.ofp) for the Oppo watch (41mm). And since I've successfully unlock the bootloader, I wanted to extract the boot.img from the firmware in order to pach it with magisk.

But when I run ofp_qc_extract.py and ofp_mtk_decrypt.py I have the following error

ofp_mtk_decrypt.py
```
b'ab3f76d7989207f2' b'2bf515b3a9737835'
Unknown key. Please ask the author for support :)
```

For ofp_qc_extract.py 

```
Unknown key. Aborting
```
 
There is another way to bruteforce the key?

**Comment by bkerler** [comment]
Can you upload the msmdownloadtool and ofp for it ?

**Comment by ShinoNuma** [comment]
Hey!

Yes, sure.

Here is the link:

```
https://drive.google.com/file/d/1AxDmw2OLeNlvGUa5oO4FSudgEYNpN0sA/view?usp=sharing
```

Let me know if you need anything else.

**Comment by bkerler** [comment]
Solved with commit 821e0ee

**Comment by ShinoNuma** [comment]
Awesome!

Thanks for all!

**Comment by MlgmXyysd** [comment]
> Hey!
> 
> Yes, sure.
> 
> Here is the link:
> 
> ```
> https://drive.google.com/file/d/1AxDmw2OLeNlvGUa5oO4FSudgEYNpN0sA/view?usp=sharing
> ```
> 
> Let me know if you need anything else.

Hi, can you get OPPO Watch China firmware? may I can do something crossflash

**Comment by ShinoNuma** [comment]
Hmmm not sure about it, I've created this gist file :
```
https://gist.github.com/ShinoNuma/c4746c3a93928433200f16f8ecf2da49
```

Hope it will help you.
