### ISSUE TITLE
Unknown pagesize

### ISSUE THREAD

**Issue by MlgmXyysd** [bkerler/oppo_decrypt#39]
`29419OW19W12EU_11_A.36_200924_d784fa8b_MCU_2009051806.ofp` in https://gist.github.com/ShinoNuma/c4746c3a93928433200f16f8ecf2da49 provided by @ShinoNuma

May other ofp have such problems too @bkerler

**Comment by bkerler** [comment]
I will have a look

**Comment by MlgmXyysd** [comment]
> I will have a look

Have you ever thought about cracking the login verification of MsmDownloadTool account directly?

**Comment by bkerler** [comment]
I don't crack logins or applications, that's clearly illegal. Regarding the ofp, this doesn't have a typical ofp structure or is broken.
