### ISSUE TITLE
MSM stuck at "Downloading op2.img to op2" - Reencrypted ops

### ISSUE THREAD

**Issue by vitogga** [bkerler/oppo_decrypt#43]
When I try to install an ops reencrypted, the msmdownload tool gets stuck at Status of comunication: "Downloading op2.img to op2", Time: 8s.
![Sin título](https://user-images.githubusercontent.com/86333177/123364958-588b9580-d543-11eb-8895-a425fcfe850b.jpg)

**Comment by vitogga** [comment]
It is not related to this tool.

**Comment by SagarMakhar** [comment]
@vitogga were you able to boot from reencrypted ops ?
