### ISSUE TITLE
Realme 3 18601_RMX1821EX_11_C.14.ofp support

### ISSUE THREAD

**Issue by ameyjoshi3068** [bkerler/oppo_decrypt#45]
Please bring support ASAP

**Comment by ameyjoshi3068** [comment]
You may ask me for key or link

**Comment by yssreddy1961** [comment]
tested,now working with latest release 3.5.2 edl
 python3 ofp_qc_decrypt.py ../18601_RMX1821EX_11_C.14.ofp  ../oppo2
Zip file detected, trying to decrypt files
Extracting boot.img to ../oppo2
Extracting dtbo.img to ../oppo2
Extracting FlashingConfig.xml to ../oppo2
Extracting recovery.img to ../oppo2
Extracting system.img to ../oppo2
Extracting vendor.img to ../oppo2
7][p
Files extracted to ../oppo2  
ISSUE CAN BE CLOSED

**Comment by ameyjoshi3068** [comment]
Thank you very much
