### ISSUE TITLE
[Realme 8 PRO]: Unknown key. Please ask the author for support :)

### ISSUE THREAD

**Issue by daeSundae** [bkerler/oppo_decrypt#47]
I am getting this error output when i try to decrypt Realme 8 PRO ofp with the link bellow:
![image](https://user-images.githubusercontent.com/72439241/131582960-436465df-d0f2-4e9c-a55a-eeb7aa9a74a2.png)

`b'ab3f76d7989207f2' b'2bf515b3a9737835'
Unknown key. Please ask the author for support :)
`
https://fileload.coloros.com/490144RMX3081GDPR_11_A.30_2021042200210000.zip

**Comment by yssreddy1961** [comment]
extract zip file and do 
./ofp_qc_decrypt.py RMX3081GDPR_11_A.30_2021042200210000.ofp outputDir
extracting ok
