### ISSUE TITLE
Unbrick oneplus 5t with save userdata

### ISSUE THREAD

**Issue by panty90** [bkerler/oppo_decrypt#5]
I need to unbrick my oneplus 5t without loss my user data. All oneplus 5t unbrick tools have firmware in one file .ops. I need extract it and then I will try this guide to save my data. https://forum.xda-developers.com/oneplus-3t/how-to/unbrick-tool-3t-unbrick-data-babloo-t3737791
Please, help me!

**Comment by btuhin17** [comment]
Whats you actually problem please explain

**Comment by btuhin17** [comment]
But its not possible to safe your user data..sorry..all unbrick tools
method your data will be erase..after flash

**Comment by btuhin17** [comment]
Your bootloader is unlocked or lock

**Comment by panty90** [comment]
No. I find two guides for oneplus one and for oneplus 3t where userdata was saved.

**Comment by panty90** [comment]
Bootloader is lock

**Comment by panty90** [comment]
One of it is where https://forum.xda-developers.com/oneplus-3t/how-to/unbrick-tool-3t-unbrick-data-babloo-t3737791

**Comment by btuhin17** [comment]
Are you indian??

**Comment by btuhin17** [comment]
Or speak hindi or any indian languages

**Comment by panty90** [comment]
In this guide for oneplus 3t firmware have separated files: boot, recovery and etc. In all unbrick tools for oneplus 5t firmware is in one file .ops. I need to extract it and after that change process loading without  erase userdata.
No)

**Comment by btuhin17** [comment]
Yes...only OnePlus 3 & 3t firmware is separate part by part..but after oreo
firmware.. OnePlus combined there firmware in .ops file..its not possible
to extract (any normal user)only can OnePlus official developer or any
hardcore software programmer can decrypt this firmware.. becouse this
prosser is very complicated..

**Comment by panty90** [comment]
So I described the problem here, where they offer codes for unpacking .ops files. Oneplus support says that not possible too but I know another. It their falt, that my phone is bricked after last update. Files very important for me and I can't erase it.

**Comment by btuhin17** [comment]
Then it not possible to recover without erase your data...

**Comment by btuhin17** [comment]
Or search on YouTube or Google "how to backup my phone data from edl 9008
mode

**Comment by panty90** [comment]
Thank you)
