### ISSUE TITLE
merge the super.img

### ISSUE THREAD

**Issue by qianmo-xw** [bkerler/oppo_decrypt#51]
Some OPPO MTK devices ofp file,after unpack ofp file.Will show super0.xxx.img super1.xxx.img，and have a super_map.scv file,this file include super file address. so can we support auto merge all the super file to super.img？
device is oppo a93，if you don't have ofp file. I can provide one for you.

**Comment by MlgmXyysd** [comment]
Automatic merging destroys the file structure. You can merge them manually.

**Comment by qianmo-xw** [comment]
> Automatic merging destroys the file structure. You can merge them manually.

Which tool can merge them manually,In fact, I just don't know what tools can

**Comment by MlgmXyysd** [comment]
> > Automatic merging destroys the file structure. You can merge them manually.
> 
> Which tool can merge them manually,In fact, I just don't know what tools can

https://github.com/bkerler/oppo_decrypt/issues/41#issuecomment-873375685

**Comment by qianmo-xw** [comment]
> > > 自动合并会破坏文件结构。您可以手动合并它们。
> > 
> > 
> > 哪个工具可以手动合并，其实我就是不知道什么工具可以
> 
> [第41章（评论）](https://github.com/bkerler/oppo_decrypt/issues/41#issuecomment-873375685)

Ok，Thank you.
