### ISSUE TITLE
[MTK] How to obtain the decrypt keys?

### ISSUE THREAD

**Issue by DavidWithTuxedo** [bkerler/oppo_decrypt#64]
Dear bkerler, sorry to disturb you in your busy schedule.
Unlike the "ozip", there is no related thread about getting keys for unsupported "ofp" files. Taking it into cosideration may add more support devices, then making this repo great.

Problems like this:
```bash
b'ab3f76d7989207f2' b'2bf515b3a9737835'
Unknown key. Please ask the author for support :)
```
Here is the DownloadTool.exe file that is compatible with "ofp". [DownloadTool.exe](https://u.pcloud.link/publink/show?code=XZI5vFVZF1o4con97xpJlNr5dMDRt86iPG37) 
Would you please let us know what should we do for this "exe"?

Thanks in advance!

**Comment by nagendra-d** [comment]
@DavidWithTuxedo did you get the key ?
