### ISSUE TITLE
Help Please ! a fix needed for newbies like me

### ISSUE THREAD

**Issue by Ldev007** [bkerler/oppo_decrypt#7]
Hello ! your scripts are just awesome ! and helped me alot already but I'm stuck at an stage which is "OFP Extraction". The thing is I don't have any idea about "startoffset" or "length" I tried researching but couldn't understand at all. Pardon my dumbness. Maybe I'm just not able to get in the right direction..

So, as an solution I thought to ask you out like what about if you can create another script which could just extract the whole .ofp file or you can also give options within the script itself to choose between complete extraction or offset specific extraction ? whatever you think about it please reply it's ok if it's not possible but please do reply.

Thanks,
Ldev

**Comment by nathanvdh** [comment]
This a very specific set of very useful tools - both this and the ozip decrypter, but the average user has not really any documentation to go on. So you end up with all these "HELP ME PLEASE!!" issues. A short wiki or more detailed readme would be greatly appreciated.

**Comment by bkerler** [comment]
The ofp decrypter no longer works, that's why it's not maintained and documented right now.
