### ISSUE TITLE
Decrypt: error on hashes. File might be broken!

### ISSUE THREAD

**Issue by igjnaj** [bkerler/oppo_decrypt#91]
Decrypt won't work?
LOGS :
C:\Users\Administrator\Desktop\oppo_decrypt-master>python ofp_qc_decrypt.py CPH1931EX_11_C.84_220830_9dd71c8f.ofp C:\Users\Administrator\Desktop\oppo_decrypt-master\extracted
Saving ProFile.xml

Extracting BTFM.bin
Decrypt: success! (md5: verified | sha256: verified)

Extracting BTFM_ufs.bin
Decrypt: error on hashes. File might be broken!

Extracting DRIVER.ISO
Decrypt: error on hashes. File might be broken!

Extracting NON-HLOS.bin
Decrypt: error on hashes. File might be broken!

Extracting NON-HLOS_ufs.bin
Decrypt: error on hashes. File might be broken!

Extracting abl.elf
Decrypt: error on hashes. File might be broken!

Extracting boot.img
Decrypt: error on hashes. File might be broken!

Extracting cache.img
Decrypt: error on hashes. File might be broken!

Extracting cdt_engineering_release.img
Decrypt: error on hashes. File might be broken!

Extracting cmnlib.mbn
Decrypt: error on hashes. File might be broken!

Extracting cmnlib64.mbn
Decrypt: error on hashes. File might be broken!

Extracting ddr.img
Decrypt: error on hashes. File might be broken!

Extracting devcfg.mbn
Decrypt: error on hashes. File might be broken!

Extracting dpAP.mbn
Decrypt: error on hashes. File might be broken!

Extracting dspso.bin
Decrypt: error on hashes. File might be broken!

Extracting dtbo.img
Decrypt: error on hashes. File might be broken!

Extracting dynamic_nvbk.bin
Decrypt: error on hashes. File might be broken!

Extracting emmc_fw.bin
Decrypt: error on hashes. File might be broken!

Extracting gpt_backup0.bin
Decrypt: error on hashes. File might be broken!

Extracting gpt_backup0_ufs.bin
Decrypt: error on hashes. File might be broken!

Extracting gpt_backup1_ufs.bin
Decrypt: error on hashes. File might be broken!

Extracting gpt_backup2.bin
Decrypt: error on hashes. File might be broken!

Extracting gpt_backup2_ufs.bin
Decrypt: error on hashes. File might be broken!

Extracting gpt_backup3_ufs.bin
Decrypt: error on hashes. File might be broken!

Extracting gpt_backup4_ufs.bin
Decrypt: error on hashes. File might be broken!

Extracting gpt_backup5_ufs.bin
Decrypt: error on hashes. File might be broken!

Extracting gpt_main0.bin
Decrypt: error on hashes. File might be broken!

Extracting gpt_main0_ufs.bin
Decrypt: error on hashes. File might be broken!

Extracting gpt_main1_ufs.bin
Decrypt: error on hashes. File might be broken!

Extracting gpt_main2.bin
Decrypt: error on hashes. File might be broken!

Extracting gpt_main2_ufs.bin
Decrypt: error on hashes. File might be broken!

Extracting gpt_main3_ufs.bin
Decrypt: error on hashes. File might be broken!

Extracting gpt_main4_ufs.bin
Decrypt: error on hashes. File might be broken!

Extracting gpt_main5_ufs.bin
Decrypt: error on hashes. File might be broken!

Extracting hyp.mbn
Decrypt: error on hashes. File might be broken!

Extracting imagefv.elf
Decrypt: error on hashes. File might be broken!

Extracting km4.mbn
Decrypt: error on hashes. File might be broken!

Extracting logfs_ufs_8mb.bin
Decrypt: error on hashes. File might be broken!

Extracting metadata.img
Decrypt: error on hashes. File might be broken!

Extracting oppo19321.bin
Decrypt: error on hashes. File might be broken!

Extracting oppo_sec.mbn
Decrypt: error on hashes. File might be broken!

Extracting opporeserve2.img
Decrypt: error on hashes. File might be broken!

Extracting persist.img
Decrypt: error on hashes. File might be broken!

Extracting qupv3fw.elf
Decrypt: error on hashes. File might be broken!

Extracting recovery.img
Decrypt: error on hashes. File might be broken!

Extracting rpm.mbn
Decrypt: error on hashes. File might be broken!

Extracting sec_smt.dat
Decrypt: error on hashes. File might be broken!

Extracting splash.img
Decrypt: error on hashes. File might be broken!

Extracting static_nvbk.bin
Decrypt: error on hashes. File might be broken!

Extracting storsec.mbn
Decrypt: error on hashes. File might be broken!

Extracting system.img
Decrypt: error on hashes. File might be broken!

Extracting tz.mbn
Decrypt: error on hashes. File might be broken!

Extracting uefi_sec.mbn
Decrypt: error on hashes. File might be broken!

Extracting userdata.img
Decrypt: error on hashes. File might be broken!

Extracting vbmeta.img
Decrypt: error on hashes. File might be broken!

Extracting vendor.img
Decrypt: error on hashes. File might be broken!

Extracting xbl.elf
Decrypt: error on hashes. File might be broken!

Extracting xbl_config.elf
Decrypt: error on hashes. File might be broken!

Extracting Setting.xml
Decrypt: error on hashes. File might be broken!

Extracting Projectconfig.xml
Decrypt: error on hashes. File might be broken!

Extracting prog_firehose_ddr.elf
Decrypt: error on hashes. File might be broken!

Extracting rawprogram0.xml
Decrypt: error on hashes. File might be broken!

Extracting rawprogram2.xml
Decrypt: error on hashes. File might be broken!

Extracting patch0.xml
Decrypt: error on hashes. File might be broken!

Extracting patch2.xml
Decrypt: error on hashes. File might be broken!

Extracting ChainedTableOfDigests_19321_all.bin
Decrypt: error on hashes. File might be broken!

Extracting ChainedTableOfDigests_19321_persist_no_userdata_yes.bin
Decrypt: error on hashes. File might be broken!

Extracting ChainedTableOfDigests_19321_persist_yes_userdata_yes.bin
Decrypt: error on hashes. File might be broken!

Extracting ChainedTableOfDigests_19321_persist_yes_userdata_no.bin
Decrypt: error on hashes. File might be broken!

Extracting ChainedTableOfDigests_19321_persist_no_userdata_no.bin
Decrypt: error on hashes. File might be broken!

Extracting DigestsToSign_19321_all.bin.mbn
Decrypt: error on hashes. File might be broken!

Extracting DigestsToSign_19321_persist_no_userdata_yes.bin.mbn
Decrypt: error on hashes. File might be broken!

Extracting DigestsToSign_19321_persist_yes_userdata_yes.bin.mbn
Decrypt: error on hashes. File might be broken!

Extracting DigestsToSign_19321_persist_yes_userdata_no.bin.mbn
Decrypt: error on hashes. File might be broken!

Extracting DigestsToSign_19321_persist_no_userdata_no.bin.mbn
Decrypt: error on hashes. File might be broken!

Extracting prog_firehose_ddr_ufs.elf
Decrypt: error on hashes. File might be broken!

Extracting rawprogram0_ufs.xml
Decrypt: error on hashes. File might be broken!

Extracting rawprogram1_ufs.xml
Decrypt: error on hashes. File might be broken!

Extracting rawprogram2_ufs.xml
Decrypt: error on hashes. File might be broken!

Extracting rawprogram3_ufs.xml
Decrypt: error on hashes. File might be broken!

Extracting rawprogram4_ufs.xml
Decrypt: error on hashes. File might be broken!

Extracting rawprogram5_ufs.xml
Decrypt: error on hashes. File might be broken!

Extracting patch0_ufs.xml
Decrypt: error on hashes. File might be broken!

Extracting patch1_ufs.xml
Decrypt: error on hashes. File might be broken!

Extracting patch2_ufs.xml
Decrypt: error on hashes. File might be broken!

Extracting patch3_ufs.xml
Decrypt: error on hashes. File might be broken!

Extracting patch4_ufs.xml
Decrypt: error on hashes. File might be broken!

Extracting patch5_ufs.xml
Decrypt: error on hashes. File might be broken!

Extracting ChainedTableOfDigests_19321_all_ufs.bin
Decrypt: error on hashes. File might be broken!

Extracting ChainedTableOfDigests_19321_persist_no_userdata_yes_ufs.bin
Decrypt: error on hashes. File might be broken!

Extracting ChainedTableOfDigests_19321_persist_yes_userdata_yes_ufs.bin
Decrypt: error on hashes. File might be broken!

Extracting ChainedTableOfDigests_19321_persist_yes_userdata_no_ufs.bin
Decrypt: error on hashes. File might be broken!

Extracting ChainedTableOfDigests_19321_persist_no_userdata_no_ufs.bin
Decrypt: error on hashes. File might be broken!

Extracting ChainedTableOfDigests_provision_hynix.bin
Decrypt: error on hashes. File might be broken!

Extracting ChainedTableOfDigests_provision_samsung.bin
Decrypt: error on hashes. File might be broken!

Extracting ChainedTableOfDigests_provision_micron.bin
Decrypt: error on hashes. File might be broken!

Extracting DigestsToSign_19321_all_ufs.bin.mbn
Decrypt: error on hashes. File might be broken!

Extracting DigestsToSign_19321_persist_no_userdata_yes_ufs.bin.mbn
Decrypt: error on hashes. File might be broken!

Extracting DigestsToSign_19321_persist_yes_userdata_yes_ufs.bin.mbn
Decrypt: error on hashes. File might be broken!

Extracting DigestsToSign_19321_persist_yes_userdata_no_ufs.bin.mbn
Decrypt: error on hashes. File might be broken!

Extracting DigestsToSign_19321_persist_no_userdata_no_ufs.bin.mbn
Decrypt: error on hashes. File might be broken!

Extracting DigestsToSign_provision_hynix.bin.mbn
Decrypt: error on hashes. File might be broken!

Extracting DigestsToSign_provision_samsung.bin.mbn
Decrypt: error on hashes. File might be broken!

Extracting DigestsToSign_provision_micron.bin.mbn
Decrypt: error on hashes. File might be broken!

Extracting provision_hynix.xml
Decrypt: error on hashes. File might be broken!

Extracting provision_samsung.xml
Decrypt: error on hashes. File might be broken!

Extracting provision_micron.xml
Decrypt: error on hashes. File might be broken!

Done. Extracted files to C:\Users\Administrator\Desktop\oppo_decrypt-master\extracted

C:\Users\Administrator\Desktop\oppo_decrypt-master>

**Comment by MrSaatci** [comment]
And how did you solve this?
